"""add new column

Revision ID: 0ec6f57d2eab
Revises: 7116e5dc36d0
Create Date: 2021-12-08 20:28:34.079700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec6f57d2eab'
down_revision = '7116e5dc36d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_path', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_path')
    # ### end Alembic commands ###
