"""add avatar upload

Revision ID: 896644b72293
Revises: 7b1071707c9c
Create Date: 2021-12-08 17:17:47.547539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896644b72293'
down_revision = '7b1071707c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_avatar', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_avatar')
    # ### end Alembic commands ###
